# Generated by Django 3.0 on 2021-03-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20210124_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(blank=True, default='man.png', null=True, upload_to='profile_pic'),
        ),
    ]
