# Generated by Django 3.0 on 2020-10-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20201005_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='/media/img/cover.jpg', null=True, upload_to='img'),
        ),
    ]
