# Generated by Django 3.0 on 2020-10-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_auto_20201005_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/cover.jpg', null=True, upload_to='img'),
        ),
    ]
